chore(ci): add golangci linter
UpCloudLtd/terraform-provider-upcloud pull request #142
Opened 2021-05-10 10:58 UTC by kaminek

Signed-off-by: Amine Kherbouche <kaminek92@gmail.com>

2021-05-12 08:30 UTC, moitias commented
:raised_hands: LGTM :+1:

2021-05-12 09:45 UTC, moitias approved these changes

2021-05-12 10:25 UTC, moitias requested changes
We should at least;

- enable go fmt in golangci-lint
- add pre-commit hooks that run the same linters

before merging

2021-05-12 10:31 UTC, scop commented on .github/workflows/lint.yml
> +          version: v1.37.1
If there's no reason to install an older one:

```suggestion
          version: v1.40.0
```

2021-05-12 10:34 UTC, scop commented
>     * enable go fmt in golangci-lint

Tested adding `gofmt` to the config locally, it resulted in no new findings. But agree we should add it if there's no strong/particular reason not to.

2021-05-14 07:16 UTC, moitias approved these changes

2021-05-14 07:17 UTC, merged